// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OsuTracker.Web.Data;

#nullable disable

namespace OsuTracker.Web.Data.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    partial class TrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("OsuTracker.Web.Data.Entities.Beatmap", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ar")
                        .HasColumnType("REAL");

                    b.Property<long>("BeatmapsetId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cs")
                        .HasColumnType("REAL");

                    b.Property<string>("DifficultyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("Hp")
                        .HasColumnType("REAL");

                    b.Property<int?>("MaxCombo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Od")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("SeenInRunAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("StarRating")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeatmapsetId")
                        .HasDatabaseName("ix_beatmap_set");

                    b.HasIndex("Mode", "StarRating")
                        .HasDatabaseName("ix_beatmap_mode_stars");

                    b.HasIndex("Mode", "Status")
                        .HasDatabaseName("ix_beatmap_mode_status");

                    b.ToTable("Beatmaps");
                });

            modelBuilder.Entity("OsuTracker.Web.Data.Entities.Beatmapset", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double>("Bpm")
                        .HasColumnType("REAL");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RankedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SeenInRunAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RankedDate");

                    b.HasIndex("Status");

                    b.ToTable("Beatmapsets");
                });

            modelBuilder.Entity("OsuTracker.Web.Data.Entities.PlayCount", b =>
                {
                    b.Property<long>("BeatmapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BeatmapId");

                    b.ToTable("PlayCounts");
                });

            modelBuilder.Entity("OsuTracker.Web.Data.Entities.Score", b =>
                {
                    b.Property<long>("BeatmapId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<bool>("CountsAsPass")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLazer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxCombo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mods")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayedAtUnix")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BeatmapId");

                    b.HasIndex("PlayedAtUnix")
                        .HasDatabaseName("ix_score_played");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("OsuTracker.Web.Data.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("OsuTracker.Web.Data.Entities.SyncJob", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cursor")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsTotal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RunStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("OsuTracker.Web.Data.Entities.Beatmap", b =>
                {
                    b.HasOne("OsuTracker.Web.Data.Entities.Beatmapset", "Beatmapset")
                        .WithMany("Beatmaps")
                        .HasForeignKey("BeatmapsetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmapset");
                });

            modelBuilder.Entity("OsuTracker.Web.Data.Entities.PlayCount", b =>
                {
                    b.HasOne("OsuTracker.Web.Data.Entities.Beatmap", "Beatmap")
                        .WithOne("PlayCount")
                        .HasForeignKey("OsuTracker.Web.Data.Entities.PlayCount", "BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmap");
                });

            modelBuilder.Entity("OsuTracker.Web.Data.Entities.Score", b =>
                {
                    b.HasOne("OsuTracker.Web.Data.Entities.Beatmap", "Beatmap")
                        .WithOne("Score")
                        .HasForeignKey("OsuTracker.Web.Data.Entities.Score", "BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmap");
                });

            modelBuilder.Entity("OsuTracker.Web.Data.Entities.Beatmap", b =>
                {
                    b.Navigation("PlayCount");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("OsuTracker.Web.Data.Entities.Beatmapset", b =>
                {
                    b.Navigation("Beatmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
